/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUFIZlNnT0Jpb21KZDFJSHAwQy82T3lYL3lnRkhRS1h2M2pvQldpZEJHMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiem1Tbk16VnpGaVNGTmNOZ1VyNTY0eUNYMmQrNGp5MkRUcXVJeGUvQnh3QT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5RWxsemRJTm5JUyswQ0NIOWs5MHlpZDlPMEdOOHlEYi9SVy8rNk5pWlhZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0aDIwcGI2QUZwbHdMSGVneXlFMUdsM0NiTG04V0h5UThsdzlKUEpnVFhBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdMcVEwWVlucDQzTFVlWW10YUFiTWdKN2NrZVpwZzBLL3p4VGZIcC96Mjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik44UzJWMGZ2blA3RXFEaWs2RjdhSlhxYlluSHJsMFU5SVNxc0ljVmkyV2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUNoVHRzTTlKVVJQWmltbm5EK3c5eUdpeGVZMWE3TlQyRmtlMllweUYwMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMWxtSGNwYjhaWmFFZjVEQit3TDV0cG0wSEMzT2JjVFQ2b0NSM1RRZVQzaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhLdDRoK0ZBOWYrSHFkL2tTZTNoc2kxTE41T0gwVDg2UmJDbHVmSDVMODc3d0ViNmxEcFBaZDF2UGFlbFRvMGVtU0t4NGlucVVFUXZYUkpQQlhjVEFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzEsImFkdlNlY3JldEtleSI6Im1rTWlpejNmQ0J2STZhaG9xMlJFdytpVFRLbUsxeEVnZjFaZmp1dmsrZVk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkdWbVRYWGM4Um5LTllLLXpKSTk4blEiLCJwaG9uZUlkIjoiYWI4M2E2ODctMTc4YS00MmQzLTlhMjMtMTc0ODY3M2E0MDQ4IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNRMHJPSXFGN2tndkU5cUwxZENtWWp0cWV6TT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJiMXVpZG5tRTlaWVAvV2ZtOVhvbnZ4ZkZwc2s9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiNEpFS1A3U1MiLCJtZSI6eyJpZCI6Ijk0NzY2MDM0OTQzOjIwQHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNeXB6ZGtCRUtDWjc3Z0dHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ2cUFvdmhDY21DTmYwZVdZRi9sa0xBQmxpWWZLTXhLSHR3eWVpM0V5SkM4PSIsImFjY291bnRTaWduYXR1cmUiOiJON0NXeFFFMkpsV3FDYjE4cjVXdjFjUkNENHZ1bVlDQUhGaGFyUTh1V2lJNlBWTStSN1ZSMFdMTzh5TExnNEQxQUl1UXloNjJYZzM0ZUVJa2Q5Z1BEdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiK080T2l3bndNc25QTnZ4Wll0STl3NFlJNnhuY2VsWWdmdkh0aXFuWHlKaUt5RFBxK1ViL2k5VHhuZXVZWTJKdGV6UXRoL2hhM09PQWxoS1NiS1I4Qnc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NjAzNDk0MzoyMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJiNmdLTDRRbkpnalg5SGxtQmY1WkN3QVpZbUh5ak1TaDdjTW5vdHhNaVF2In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5ODc1MTE3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdEaiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "94";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '94754625969';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
